site_name: The Atomist Documentation
site_description: Documentation for the Atomist Developer Platform
site_author: The Atomist Team
copyright: '&copy; 2017 Atomist, Inc.'
extra:
  main_site_url: https://www.atomist.com/
theme: material
site_favicon: images/favicon.ico
extra:
  logo: images/atomist-logo-horiz-reversed.svg
  palette:
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  social:
    - type: medium
      link: https://the-composition.com/
    - type: github
      link: https://github.com/atomist
    - type: twitter
      link: https://twitter.com/atomist
    - type: slack
      link: https://join.atomist.com/
extra_css:
  - stylesheets/extra.css
google_analytics:
  - UA-74966852-1
  - auto
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false, linenums=false)
  - def_list
  - footnotes
  - meta
  - smarty
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
repo_name: Rug
repo_url: https://github.com/atomist/rug
pages:
- Overview:
  - About Atomist: index.md
  - Concepts: concepts.md
  - Capabilities: capabilities.md
  - Benefits: benefits.md
- Getting Started: 
  #- Quick Start: getting-started/quickstart.md
  - Step By Step:
    - Introduction: getting-started/index.md
    - Prerequisites: getting-started/prerequisites.md
    - Invite Atomist to Slack: getting-started/invite-atomist-to-slack.md
    - Connect Atomist to GitHub: getting-started/connect-atomist-to-github.md
    - Putting Atomist to Work: getting-started/putting-atomist-to-work.md
    - Connect Atomist to CI: getting-started/connect-atomist-to-ci.md
    - Build Your Own Development Automation: getting-started/build-your-own-development-automation.md
- Use Cases:
  - How To Use Atomist: use-cases/index.md
- User Guide:
    - Introduction: user-guide/index.md
    - Rug:
        - Introduction : user-guide/rug/index.md
        - Runtime: user-guide/rug/runtime.md
        - Handlers: user-guide/rug/handlers.md
        - Commands: user-guide/rug/commands.md
        - Editors: user-guide/rug/editors.md
        - Generators: user-guide/rug/generators.md
        - Reviewers: user-guide/rug/reviewers.md
        - Extensions: user-guide/rug/extensions.md
        - Path Expressions: user-guide/rug/path-expressions.md
        - Microgrammars: user-guide/rug/microgrammars.md
        - Templates: user-guide/rug/templates.md
        - Tests: user-guide/rug/tests.md
        - Projects: user-guide/rug/projects.md
        - Archives: user-guide/rug/archives.md
#        - Development: user-guide/rug/development.md
        - Lifecycle: user-guide/rug/lifecycle.md
        - Conventions: user-guide/rug/conventions.md
    - Integrations:
        - Overview: user-guide/integrations/index.md
        - Slack: user-guide/integrations/slack.md
        - GitHub.com: user-guide/integrations/github.md
        - Travis CI: user-guide/integrations/travis-ci.md
        - Jenkins: user-guide/integrations/jenkins.md
    - Interfaces:
        - Introduction: user-guide/interfaces/index.md
        - Bot: user-guide/interfaces/bot.md
        - CLI:
            - Overview: user-guide/interfaces/cli/index.md
            - Installation: user-guide/interfaces/cli/install.md
            - Basics: user-guide/interfaces/cli/basics.md
            - Using Rugs: user-guide/interfaces/cli/using-rugs.md
            - Developing Rugs: user-guide/interfaces/cli/developing-rugs.md
    - Permissions:
        - Overview: user-guide/permissions/index.md
        - Slack Scopes: user-guide/permissions/slack.md
        - GitHub Scopes: user-guide/permissions/github.md
- Reference Documentation:
    - Overview: reference/index.md
    - Rug:
        - Overview: reference/rug/index.md
        - Rugs:
            - Overview: reference/rug/rugs.md
#            - Handlers: reference/rug/handlers.md
#            - Commands: reference/rug/commands.md
            - Editors: reference/rug/editors.md
            - Generators: reference/rug/generators.md
#            - Reviewers: reference/rug/reviewers.md
            - Path Expressions: reference/rug/path-expressions.md
#            - Microgrammars: reference/rug/microgrammars.md
#            - Templates: reference/rug/templates.md
#            - Tests: reference/rug/tests.md
#            - Archives: reference/rug/archives.md
        - Extensions: reference/rug/extensions.md
        - DSL:
            - Overview: reference/rug/dsl/index.md
            - Syntax: reference/rug/dsl/syntax.md
            - Using JavaScript: reference/rug/dsl/javascript.md
    - Rug CLI: reference/rug-cli/index.md
- Why Atomist:
  - Automate All The Things: why-atomist/automate-all-the-things.md